GET http://localhost:3001/login

###

GET http://localhost:3001

### 
# create user
POST http://localhost:3001/api/signup
Content-Type: application/json

{
    "username":"lewy192",
    "enteredPassword":"test",
    "firstName":"lewis",
    "lastName":"hill",
    "email":"lewis.test@email.com"

}


###
GET http://localhost:3001/api/post/7


### 
POST http://localhost:3001/api/post/create
Content-Type: application/json

{
    "postTitle":"this is a testasdf3",
    "postContent": "testing nbumer 3",
    "userId":1
}